#+TITLE: Runbox
#+SUBTITLE: [Run] in Tool[Box]
#+AUTHOR: Antonio Romano
#+TEXINFO_FILENAME: runbox.info
#+TEXINFO_DIR_CATEGORY: Emacs
#+TEXINFO_DIR_TITLE: Runbox: (runbox).
#+TEXINFO_DIR_DESC: [Run] in Tool[Box]
#+OPTIONS: toc:t

Runbox provides TRAMP-redirected variants of common Emacs commands (e.g. =runbox-shell= for =shell=, =runbox-eglot= for =eglot=) that spawn their subprocess in a different environment than the one implied by the current buffer. Given a buffer working on a local directory, each variant spawns its subprocess under a TRAMP-prefixed version of that directory, leaving the originating buffer's default-directory untouched.

#+begin_export texinfo
@cartouche
@strong{Note:} This package is ALPHA stage software. It has
not been tested thoroughly and bugs are likely to occur.
@end cartouche
#+end_export

The main use case of this package is to transparently run LSP clients, shells, compilation commands, etc... against binaries residing in [[https://github.com/antrmn/tramp-flatpak-host][Toolbox]] containers whilst operating in local buffer. Although it tries to generalize the solution to accomodate any TRAMP backend which oparates like it and has an 1:1 mapping with the host's home directory (like the backend for [[https://distrobox.it/][Distrobox]] or [[https://github.com/antrmn/tramp-flatpak-host][fphost]], to run commands outside the Flatpak sandbox).

The advantage in doing so is are:

- No need to jump between =/foo.c= and =/toolbox:MyToolbox:/foo.c= editing buffer, which point to the same file but are seen by Emacs by different paths and projects.
- Process spawning environment is not an *all or nothing deal*: some binaries are run from the host (VC, spell checkers), proejct specific toolchain are run from the Toolbox container. Still, no buffer switching needed.


Running binaries in containers is useful for users using immutable distros (e.g Fedora Silverblue) who cannot conveniently (or simply do not want to) install toolchains on their host system. It is also useful in general for anyone wanting to declaratively define their project's build environment.

[[https://apps.gnome.org/Builder/][GNOME Builder]] nails this, and is the target whose UX I tried to mimic when thinking of this package. It is possible to define a per-project build environment, and all compilation commands as well as LSP requests are redriected to it. The git handling as well as the spell checking still reside on the host as they are considered "editor coupled".

Emacs provides TRAMP out-of-the-box, which is an incredibly versatile facility for transparently accessing remote environments including containers. However, its usage semantics kind of fall short when trying to access an environment such as a toolbox container: all the user files are treated as different, despite being the same as the host. Accessing the container is an all or nothing deal: you can only use the binaries in there,.

This may benefit users of immutable operating systems who may not want to install toolchains on the host operating systems but keep them separated in containers. Runbox covers Toolbox, Distrobox and alike container solutions due to their ease of use, trivial and close to non-existent life-cycle management and 1:1 path mapping.


* Installation

To install the package, 

#+begin_example
  M-x package-vc-install https://github.com/antrmn/runbox.el.git
#+end_example

Emacs 30.1 or later is required.

* Usage
** Setting the environment
:PROPERTIES:
:id:       setting-environment
:END:


To use runbox, =runbox-environment= must be set and =default-directory= (current directory) must be under =runbox-bind-mount=.

#+vindex: runbox-environment
- User Option: =runbox-environment= ::
  the target environment for Runbox commands.

  If set, it takes a =tramp-file-name= struct as obtained by =(tramp-dissect-file-name)=. Its =localname= slot is ignored.

  It can be set interactively with a string provided input through /Customize/ facilties:
    + =customize-set-value= to set it buffer-locally
    + =customize-set-variable= to set it globally
    + =customize-dirlocals= or =project-customize-dirlocals= to set it scoped to a directory.
        - May be unsafe as a file-local variable. See [[id:environment-safety][=Runbox-environment= as a safe file-local variable]].

#vindex: runbox-bind-mount
- Constant: =runbox-bind-mount= ::
  Local host path bind-mounted into the routed environment.  Defaults to the host user's home directory. May be declared as a variable in the future.



When setting the environment ensure that your TRAMP method of choice is enabled. Toolbox is provided out of the box in Emacs 30, but it has to be manually enabled:

#+begin_example
  M-x tramp-enable-method toolbox
#+end_example


When =runbox-environment= is correctly set and =default-directory= points to a valid path, an indicator in the mode-line is shown and runbox commands can be used. One such example is =runbox-shell= which runs =shell= in the context of the specified environment. Other commands are listed in [[id:runbox-commands][Runbox dispatcher commands/functions]].


** Defining a leader key

It is possible define a leader key so that any key sequence issued right after will spawn its associated runbox equivalent command, if any. To do so, bind the desired key-sequence for the leader key to =runbox-any-command=.

#+findex: runbox-any-command
- Command: =runbox-any-command= ::
  Reads the next key sequence and runs the runbox-equivalent of the command bound to it, if any.


Such is an example that sets =C-z= as a leader key and =C-x t= for shell:

#+begin_src emacs-lisp
  (bind-keys ("C-z" . runbox-any-command)
             ("C-x t" . shell))
#+end_src

With the above example, issuing =C-z C-x t= will invoke the =runbox-shell= command.

Please note: =runbox-any-command= only works for event from the top-level command event loop: doing `C-z M-x shell` won't work as regular `shell` command will be invoked.

** Enabling automatic command dispatch 

Instead of a leader key, you can modally choose to replace every issued command with their  runbox counterparts, if any:


#+findex: runbox-auto-mode
- Minor mode: =runbox-auto-mode= ::
  when non-nil, replaces the issued commands with their runbox counterpart.

  The replacement occurs only when =runbox-environment= is set and valid (See [[id:setting-environment][Setting the environment]])

#+findex: global-runbox-auto-mode
#+vindex: global-runbox-auto-mode
- Global minor mode: =global-runbox-auto-mode= ::
  

Just like with the leader key approach explained before, this suffers of the same shortcomings: only the command issued from top-level command loop are replaced. Typing `M-x shell` will still open a regular local shell.

** Runbox dispatcher commands/functions
:PROPERTIES:
:id:       runbox-commands
:END:

* Customizing

** Customizing the mode-line

By default a mode-line-construct is displayed in the =mode-line-misc-info= area when Runbox commands can be executed (see [[id:setting-environment][Setting the environment]]). Such mode-line construct's format is defined by the =runbox-mode-line= variable.

#+vindex: runbox-mode-line
- User option: =runbox-mode-line= ::
  Variable for the user facing mode-line construct for Runbox, to be added in the mode-line.


This construct has many nested constructs that allow for granular customization. Refer to its docstring.


** Labeling Runbox environments

By default, the mode-line shows the currently set =runbox-environment=. As =runbox-environment= holds a =tramp-file-name= struct, evaluating a human readable string for it is necessary.

#+variable runbox-environment-label-formatters
+ User-option: =runbox-environment-label-formatters= ::
  Alist of =(PREDICATE-FN . FORMATTER-FN)=. Both are functions of one argument, a =tramp-file-name= vector.  The first entry whose =PREDICATE-FN= returns non-nil has its =FORMATTER-FN= called to produce the label.


#+findex: runbox-environment-label
+ Function: =runbox-environment-label environment= ::
  Return a string with a human readable name for environment.
  Consults =runbox-environment-label-formatters=, as a fallback, it returns a string constructed with =tramp-make-tramp-name= minus its localname and its leading =/= and trailing =:= (for example =podman:Container=)


#+findex: runbox-environment-label-cached
+ Function: =runbox-environment-label-cached environment= ::
  Like =runbox-environment-label=, but result is cached by =environment='s identity. Useful for hot loops and mode line rendering.


** =Runbox-environment= as a safe file-local variable
:PROPERTIES:
:id:       environment-safety
:END:

By default =runbox-environment= value is safe if it is nil, if it has a safe method according to =runbox-safe-methods= or if it is a safe =tramp-file-name= according to =runbox-environment-p-functions=.


#+variable runbox-safe-methods
+ User option: =runbox-safe-methods= '("toolbox" "distrobox") ::
  A list of string with TRAMP methods deemed safe if set as file-local.

#+variable runbox-safe-environment-p-functions
+ User option: =runbox-safe-environment-p-functions= ::
  A list of 1-arg functions that take a =tramp-file-name= struct as a parameter and return non-nil if it is safe if set in a file-local variable.

#+functions runbox-environment-safe-p
+ Function: =runbox-safe-environment-p environment=
  Returns non-nil if =environment= is safe if set in a file-local variable.

* Hacking

It is possible to define new runbox dispatcher commands, although a stable API for it is not yet defined. Refer to the source code, as it is thoroughly documented.

The core dispatching logic comes from the =runbox-funcall=, a granular dispatching is done with the =runbox-with-routing= macro.

A Runbox command shall call =runbox-assert= in the directory it will work on, in both its body function and interactive form, to ensure correct state.



